config/routes.rb
HackeratiColumns::Application.routes.draw do

  resources :sentences do
    member do
      put "move_to_right"
    end
  end

  root to: "sentences#index"

end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController

  def index
    @sentences = Sentence.all
    @sentence = Sentence.new
  end

  def create
    @sentence = Sentence.create(sentence_params)
    @sentence.save!

    if request.xhr?
      render partial: "sentences/eachsentence", locals: {sentence: @sentence}
    else
      redirect_to sentences_url
    end
  end

  def move_to_right
    @sentence = Sentence.find(params[:id])
    @sentence.toggle!(:is_left)

    render partial: "sentences/eachsentence", locals: {sentence: @sentence}
  end

  private

    def sentence_params
      params.require(:sentence).permit(:body, :is_left)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AFB Columns</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="../application.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sentences/_eachsentence.html.erb
<li class="shadow">
  <form
    class="move-sentence-to-right"
    action="<%= move_to_right_sentence_url(sentence) %>"
    method="post"
    data-remote="true">

    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

    <input type="hidden" name="_method" value="put">

    <button class="sentence-red"><%= sentence.body %></button>
    <!-- <button class="sentence-unread">Turn Unred</button> -->
  </form>
</li>

app/views/sentences/_left_sentence.html.erb
<% @sentences.each do |sentence| %>
  <% if sentence.is_left? %>
    <%= render partial: "sentences/eachsentence", locals: {sentence: sentence} %>
  <% end %>
<% end %>

app/views/sentences/_right_sentence.html.erb
<% @sentences.each do |sentence| %>
  <% if !sentence.is_left? %>
    <%= render partial: "sentences/eachsentence", locals: {sentence: sentence} %>
  <% end %>
<% end %>

app/views/sentences/_sentence.html.erb
<li>
  <form
    class="move-sentence-to-right"
    action="<%= move_to_right_sentence_url(sentence) %>"
    method="post"
    data-remote="true">

    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

    <input type="hidden" name="_method" value="put">

    <button class="sentence-red">Turn Red</button>
    <button class="sentence-unread">Turn Unred</button>
  </form>

</li>

app/views/sentences/index.html.erb
<header>
  <h1>Some Favorite Quotes:</h1>
  <h2>Click on a quote to move it to the other column.</h2>
</header>

<section class="new-quote">
  <form
    action="<%= sentences_url %>"
    method="post"
    data-remote="true"
    id="new-sentence">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="sentence[is_left]" value="true">

  <textarea class="quote-textarea" name="sentence[body]"></textarea>

  <input class="submit-quote" type="submit" value="Contribute a quote!">

  </form>
</section>

<article class="group">
  <section class="column" id="left">
    <ul id="sentence-list-left">
      <%= render partial: "sentences/left_sentence" %>
    </ul>
  </section>

  <section class="column" id="right">
    <ul id="sentence-list-right">
      <%= render partial: "sentences/right_sentence" %>
    </ul>
  </section>
</article>